services:
  db:
    image: postgres:latest
    container_name: postgres-detran
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: detran
    ports:
      - "5432:5432"